skip-check:
    - CKV_AWS_115
    - CKV_AWS_116
    - CKV_AWS_117
    - CKV_AWS_158
    - CKV_AWS_173
    - CKV_AWS_18
    - CKV_AWS_21
    - CKV_AWS_53
    - CKV_AWS_54
    - CKV_AWS_55
    - CKV_AWS_56
    - CKV_AWS_68
    - CKV_AWS_86
    - CKV_SECRET_3 # Mistaking one of the resource numbers in CDK as Azure secret
