skip-check:
  - CKV_AWS_18 # Ensure the S3 bucket has access logging enabled
  - CKV_AWS_21 # Ensure the S3 bucket has versioning enabled
  - CKV_AWS_68 # CloudFront Distribution should have WAF enabled
  - CKV_AWS_86 # Ensure CloudFront Distribution has Access Logging enabled
  - CKV_AWS_111 # Ensure IAM policies does not allow write access without constraints
  - CKV_AWS_115 # Ensure that AWS Lambda function is configured for function-level concurrent execution limit
  - CKV_AWS_116 # Ensure that AWS Lambda function is configured for a Dead Letter Queue(DLQ)
  - CKV_AWS_117 # Ensure that AWS Lambda function is configured inside a VPC
  - CKV_AWS_173 # Check encryption settings for Lambda environment variable
