# Create build
FROM --platform=linux/amd64 golang:1.21.6-alpine3.19 AS build

WORKDIR /build

COPY ./go.mod ./
COPY ./go.sum ./
RUN go mod download

COPY ./src/ ./src/
RUN go build -o ./bin/apod ./src/*.go

# Create final image
FROM build

WORKDIR /app

COPY ./.env ./
COPY ./template.html ./
COPY --from=build /build/bin/ /app/bin/

CMD ["/app/bin/apod"]
