name: Deploy website

on:
    push:
        branches: [main, fix-deployment-js-bug]

jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: check static files
              run: ls -l ./static
