name: Deploy website

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: |
        sudo apt install pandoc
        cd ./infra
        npm ci
        npm run build

    - name: Run Tests
      run: |
        cd ./infra
        npm run test

    - name: Compile html articles
      run: |
        chmod +x ./scripts/createBlogPosts.sh
        ./scripts/createBlogPosts.sh

    - name: cdk deploy
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'deploy'
        working_dir: './infra'
        cdk_args: '--require-approval never'
        actions_comment: false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ACCOUNT_NUM: ${{secrets.ACCOUNT_NUM}}
        VPC_ID: ${{secrets.VPC_ID}}
        REGION: 'eu-west-2'
