name: Deploy website

on:
    push:
        branches: [main]

jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install Dependencies and build infra
              run: |
                  sudo apt-get update
                  sudo apt-get install pandoc
                  sudo apt-get install podman
                  cd ./infra
                  npm ci
                  npm run build

            - name: Compile html articles
              run: |
                  mkdir ./src/blog
                  chmod +x ./scripts/createBlogPosts.sh
                  ./scripts/createBlogPosts.sh

            - name: cdk deploy
              uses: youyo/aws-cdk-github-actions@v2
              with:
                  cdk_subcommand: "deploy"
                  working_dir: "./infra"
                  cdk_args: "--require-approval never"
                  actions_comment: false
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  ACCOUNT_NUM: ${{secrets.ACCOUNT_NUM}}
                  REGION: "eu-west-2"
