name: Lint website

on:
    pull_request:
        branches: [main]

jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.24.0

            - name: Install pre-commit Dependencies
              run: |
                  pip install pre-commit checkov
                  make pre-commit
                  make setup

            - name: Install Infra Dependencies
              run: |
                  make buildCDK

            - name: Validate pre-commit
              run: |
                  pre-commit run --all

            - name: Run Infra Tests
              run: |
                  make testCDK

            - name: Run checkov scan
              run: |
                  make checkovCDK
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  ACCOUNT_NUM: ${{secrets.ACCOUNT_NUM}}
                  REGION: "eu-west-2"

            - name: Run diff on infra
              run: |
                  make diffCDK
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  ACCOUNT_NUM: ${{secrets.ACCOUNT_NUM}}
                  REGION: "eu-west-2"
