name: Lint website

on:
    pull_request:
        branches: [main]

jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install pre-commit Dependencies
              run: |
                  pip install pre-commit checkov
                  make setup

            - name: Install Infra Dependencies
              run: |
                  cd ./infra
                  npm ci
                  npm run build

            - name: Validate pre-commit
              run: |
                  pre-commit run --all

            - name: Run Infra Tests
              run: |
                  make test

            - name: Run checkov scan
              run: |
                  make checkov
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  ACCOUNT_NUM: ${{secrets.ACCOUNT_NUM}}
                  VPC_ID: ${{secrets.VPC_ID}}
                  REGION: "eu-west-2"
