name: Lint website

on:
    pull_request:
        branches:
            - main

jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.21.6

            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install pre-commit Dependencies
              run: |
                  pip install pre-commit checkov
                  make setup

            - name: Install Infra Dependencies
              run: |
                  cd ./infra
                  npm ci
                  npm run build

            - name: Validate pre-commit
              run: |
                  pre-commit run --all

            - name: Run Apod and Infra Tests
              run: |
                  make test

            - name: Run checkov scan
              run: |
                  make checkov
